INSERT INTO Kolekcija (sezona, godina, naziv, tip) VALUES
('Jesen/Zima', 2006, 'Alcanzar', 'Haute couture'),
('Prolece/Leto', 2011, 'Estrella', 'Haute couture'),
('Prolece/Leto', 2007, 'Aceituna', 'Lingerie'),
('Prolece/Leto', 2015, 'Estrella', 'Haute couture'),
('Jesen/Zima', 2015, 'Alcanzar', 'Lingerie'),
('Prolece/Leto', 2012, 'Trougao', 'Everyday'),
('Prolece/Leto', 2007, 'Youth', 'Bridal'),
('Jesen/Zima', 2008, 'Youth', 'Cocktail time'),
('Prolece/Leto', 2010, 'Youth', 'Cocktail time'),
('Jesen/Zima', 2014, 'Youth', 'Bridal'),
('Prolece/Leto', 2011, 'Nova', 'Lingerie'),
('Prolece/Leto', 2007, 'Love', 'Haute couture'),
('Prolece/Leto', 2016, 'Paris', 'Casual'),
('Jesen/Zima', 2006, 'Trougao', 'Lingerie'),
('Prolece/Leto', 2015, 'Trougao', 'Everyday'),
('Prolece/Leto', 2013, 'Paris', 'Haute couture'),
('Prolece/Leto', 2011, 'Alcanzar', 'Everyday'),
('Prolece/Leto', 2008, 'Nova', 'Lingerie'),
('Jesen/Zima', 2007, 'Smile', 'Bridal'),
('Prolece/Leto', 2009, 'Youth', 'Haute couture'),
('Jesen/Zima', 2015, 'Smile', 'Bridal'),
('Prolece/Leto', 2013, 'Alcanzar', 'Casual'),
('Prolece/Leto', 2014, 'Estrella', 'Bridal'),
('Prolece/Leto', 2013, 'Aceituna', 'Casual'),
('Jesen/Zima', 2014, 'Paris', 'Haute couture'),
('Prolece/Leto', 2008, 'Smile', 'Bridal'),
('Prolece/Leto', 2012, 'Trougao', 'Casual'),
('Jesen/Zima', 2015, 'Fun', 'Everyday'),
('Jesen/Zima', 2007, 'Aceituna', 'Everyday'),
('Jesen/Zima', 2008, 'Youth', 'Everyday')
